---
- name: Download and extract the Mattermost Server files
  unarchive:
    src: "{{ mattermost_archive_url }}"
    dest: /opt
    remote_src: yes
    creates: /opt/mattermost

- name: Create the Mattermost system group
  group:
    name: "{{ mattermost_system_group }}"

- name: Create the Mattermost system user
  user:
    name: "{{ mattermost_system_user }}"
    comment: Mattermost system user
    group: "{{ mattermost_system_group }}"

- name: Create storage directory for files
  file:
    path: /opt/mattermost/data
    state: directory
    owner: "{{ mattermost_system_user }}"
    group: "{{ mattermost_system_group }}"
    recurse: true

- name: Set the user and group mattermost as the owner of Mattermost files
  file:
    path: /opt/mattermost
    state: directory
    owner: "{{ mattermost_system_user }}"
    group: "{{ mattermost_system_group }}"
    recurse: true

- name: "Give write permissions to the {{ mattermost_system_group }} group"
  file:
    path: /opt/mattermost
    state: directory
    mode: g+w
    recurse: true

- name: Configure Mattermost
  template:
    src: config.json.j2
    dest: /opt/mattermost/config/config.json
  become_user: "{{ mattermost_system_user }}"

- name: Setup Mattermost to use systemd for starting and stopping
  template:
    src: mattermost.service.j2
    dest: /lib/systemd/system/mattermost.service

- name: Make systemd load the new unit
  systemd:
    daemon_reload: yes

- name: Start the service
  service:
    name: mattermost.service
    state: started
    enabled: yes
