---
- name: Copy bulk data
  copy:
    src: "{{ mattermost_team_data }}"
    dest: /tmp/mattermost-team-data.jsonl
    owner: "{{ mattermost_system_user }}"
  become: yes

- name: Import bulk data
  command: |
    /opt/mattermost/bin/mattermost import bulk /tmp/mattermost-team-data.jsonl --apply
  become: yes

